local status, leaf = pcall(require, "leaf")
if (not status) then return end
local bg = "#f4f0ed"

local colors = {
  light = "#EDEBE9",
  light_dim = "#CBD7DC",
  light_dimmer = "#D3D1CC",
  light_dimmest = "#DFDDD7",
  dark = "#555f6f",
  dark_dim = "#56759A",
  dark_dimmer = "#5E99B1",
  red_light = "#EDB8C4",
  red_soft = "#EDB8C4",
  red_hard = "#AA586E",
  blue_light = "#cfd9d9",
  blue_hard = "#5e99b1",
  blue_dark = "#7593bb",
  green_hard = "#608f8e",
  green_dark = "#bdbbb6",
  purple_soft = "#a05b89",
  purple_hard = "#b0789b",
  purple_dark = "#7c6a93",
  -- LSPSaga stuff
  orange = "#AA586E",
  cyan = "#56759A",
  yellow = "#5E99B1",
  purple = "#7c6a93",
  green = "#608f8e",
  magenta = "#a05b89",
  red = "#AA586E",
  black = "#555f6f",
  gray = "#56759A",
  fg = "#56759A",
  -- yellow_soft = "#7c6a93",
  -- yellow_hard = "#7c6a93",
  -- yellow_dark = "#7c6a93",
  -- yellow_light = "#7c6a93"
}

leaf.setup({
  underlineStyle = "underline",
  commentStyle = "italic",
  functionStyle = "NONE",
  keywordStyle = "bold",
  statementStyle = "bold",
  typeStyle = "NONE",
  variablebuiltinStyle = "italic",
  transparent = false,
  colors = {
    bg0 = colors.light,
    bg_normal = colors.light,
    bg1 = colors.light_dim,
    bg2 = colors.light_dimmer,
    fg0 = colors.dark,
    fg1 = colors.dark_dim,
    fg2 = colors.dark_dimmer,
    fg3 = colors.light_dimmest,
    fg_colored_bg = colors.light,
    red0 = colors.red_light,
    red1 = colors.red_dark,
    red3 = colors.red,
    green0 = colors.green_light,
    green1 = colors.green_dark,
    yellow0 = colors.yellow_light,
    yellow1 = colors.yellow_dark,
    blue0 = colors.blue_light,
    blue1 = colors.blue_dark,
    purple0 = colors.purple_light,
    purple1 = colors.purple_dark,
    teal0 = colors.teal_light,
    teal1 = colors.teal_dark,
    -- bg_dimmer = "#EDEBE9"
  },
  overrides = {
    LineNr                  = { fg = colors.light_dimmest },
    tsxTagName              = { bg = colors.red_hard },
    TabLine                 = { bg = colors.light },
    TabLineFill             = { bg = colors.light },
    TabLineSel              = { bg = colors.light },
    Visual                  = { bg = colors.red_light },
    Comment                 = { fg = colors.light_dimmer, style = "italic" },
    Cursor                  = { bg = "#DC7786" },
    CursorLine              = { bg = "#E9E7E4" },
    WinSeparator            = { fg = colors.light, bg = colors.bg_normal, style = "NONE" },
    MatchParen              = { fg = colors.red_hard, style = "bold" },
    SpellBad                = { guisp = colors.light_dim, },
    -- String = { bg = colors.blue_light, fg = colors.green_hard },
    TSString                = { bg = colors.blue_light, fg = colors.green_hard },
    Constant                = { fg = colors.green_hard, bg = colors.blue_light },
    TSConstant              = { fg = colors.green_hard, bg = colors.blue_light },
    Number                  = { fg = colors.purple_dark, bg = colors.light_dim, style = "bold" },
    TSNumber                = { fg = colors.purple_dark, bg = colors.light_dim },
    Function                = { fg = colors.dark, style = "bold" },
    TSFunction              = { fg = colors.dark, style = "bold" },
    TSParameter             = { fg = colors.blue_hard },
    TSParameterReference    = { fg = colors.blue_hard },
    TSConstructor           = { fg = colors.dark_dim, style = "bold" },
    TSAttribute             = { fg = colors.purple_dark },
    TSTagAttribute          = { fg = colors.purple_dark },
    TSField                 = { fg = colors.blue_hard },
    TSSymbol                = { fg = colors.light_dimmer },
    TSLabel                 = { fg = colors.blue_hard },
    Statement               = { fg = colors.dark_dim, style = "NONE" },
    TSStatement             = { fg = colors.dark_dim, style = "NONE" },
    Tag                     = { fg = colors.red_hard },
    Operator                = { fg = colors.purple_soft },
    TSOperator              = { fg = colors.purple_soft },
    Include                 = { fg = colors.purple_dark },
    TSInclude               = { fg = colors.purple_dark },
    Title                   = { fg = colors.dark },
    Type                    = { fg = colors.purple_hard, style = "italic" },
    TSType                  = { fg = colors.purple_hard, style = "italic" },
    StorageClass            = { fg = colors.dark_dim },
    TSStorageClass          = { fg = colors.dark_dim },
    Structure               = { fg = colors.purple_soft },
    TSStructure             = { fg = colors.purple_soft },
    Typedef                 = { fg = colors.dark_dim },
    TSTypedef               = { fg = colors.dark_dim },
    Special                 = { fg = colors.blue_dark },
    TSSpecial               = { fg = colors.blue_dark },
    Identifier              = { fg = colors.dark },
    TSIdentifier            = { fg = colors.dark },
    TSProperty              = { fg = colors.red_hard },
    TSVariable              = { fg = colors.dark_dim },
    TSVariableBuiltin       = { fg = colors.green_hard },
    DiagnosticUnderlineWarn = {
      guisp = colors.light_dim,
    },
    DiagnosticUnderlineHint = {
      guisp = colors.light_dimmest,
    },
    DiagnosticError         = { fg = colors.red_light, style = "italic" },
    DiagnosticWarn          = { fg = colors.light_dim, style = "italic" },
    DiagnosticInfo          = { fg = colors.light_dimmest, style = "italic" },
    DiagnosticHint          = { fg = colors.light_dimmer, style = "italic" },
    FocusedSymbol           = { bg = colors.red_light },
    Pmenu                   = { bg = colors.light_dimmest },
    Folded                  = { bg = colors.light, fg = colors.light_dimmer },

    -- general
    TitleString             = { fg = colors.fg },
    TitleIcon               = { fg = colors.dark_dimmer },
    SagaBorder              = { bg = bg, fg = colors.light_dimmest },
    SagaNormal              = { bg = bg },
    SagaExpand              = { fg = colors.red },
    SagaCollapse            = { fg = colors.red },
    SagaBeacon              = { bg = colors.magenta },
    FolderName              = { fg = colors.dark_dimmer },
    -- winbar
    LspSagaWinbarSep        = { fg = colors.light_dimmer },
    LspSagaWinbarFile       = { fg = colors.dark_dim },
    LspSagaWinbarFolderName = { fg = colors.purple_dark },
    LspSagaWinbarFolderWord = { fg = colors.purple_dark },
    -- code action
    ActionPreviewNormal     = { link = 'SagaNormal' },
    ActionPreviewBorder     = { link = 'SagaBorder' },
    ActionPreviewTitle      = { fg = colors.purple, bg = bg },
    CodeActionNormal        = { link = 'SagaNormal' },
    CodeActionBorder        = { link = 'SagaBorder' },
    CodeActionText          = { fg = colors.orange },
    CodeActionNumber        = { fg = colors.green },
    -- finder
    FinderSelection         = { fg = colors.cyan, bold = true },
    FinderFileName          = { fg = colors.white },
    FinderCount             = { link = 'Label' },
    FinderIcon              = { fg = colors.cyan },
    FinderType              = { fg = colors.purple },
    --finder spinner
    FinderSpinnerTitle      = { fg = colors.magenta, bold = true },
    FinderSpinner           = { fg = colors.magenta, bold = true },
    FinderPreviewSearch     = { link = 'Search' },
    FinderVirtText          = { fg = colors.red },
    FinderNormal            = { link = 'SagaNormal' },
    FinderBorder            = { link = 'SagaBorder' },
    FinderPreviewBorder     = { link = 'SagaBorder' },
    -- definition
    DefinitionBorder        = { link = 'SagaBorder' },
    DefinitionNormal        = { link = 'SagaNormal' },
    DefinitionSearch        = { link = 'Search' },
    -- hover
    HoverNormal             = { link = 'SagaNormal' },
    HoverBorder             = { link = 'SagaBorder' },
    -- rename
    RenameBorder            = { link = 'SagaBorder' },
    RenameNormal            = { fg = colors.orange, bg = bg },
    RenameMatch             = { link = 'Search' },
    -- diagnostic
    DiagnosticBorder        = { link = 'SagaBorder' },
    DiagnosticSource        = { fg = 'gray' },
    DiagnosticNormal        = { link = 'SagaNormal' },
    DiagnosticErrorBorder   = { link = 'DiagnosticError' },
    DiagnosticWarnBorder    = { link = 'DiagnosticWarn' },
    DiagnosticHintBorder    = { link = 'DiagnosticHint' },
    DiagnosticInfoBorder    = { link = 'DiagnosticInfo' },
    DiagnosticPos           = { fg = colors.gray },
    DiagnosticWord          = { fg = colors.fg },
    -- Call Hierachry
    CallHierarchyNormal     = { link = 'SagaNormal' },
    CallHierarchyBorder     = { link = 'SagaBorder' },
    CallHierarchyIcon       = { fg = colors.purple },
    CallHierarchyTitle      = { fg = colors.red },
    -- lightbulb
    LspSagaLightBulb        = { link = 'DiagnosticSignHint' },
    -- shadow
    SagaShadow              = { bg = colors.light_dimmer },
    SagaWinbarSep           = { fg = colors.purple },
    SagaWinbarFileName      = { fg = colors.fg },
    SagaWinbarFileIcon      = { fg = colors.fg },
    SagaWinbarFolderName    = { fg = colors.fg },
    -- Outline
    OutlineIndent           = { fg = colors.magenta },
    OutlinePreviewBorder    = { link = 'SagaNormal' },
    OutlinePreviewNormal    = { link = 'SagaBorder' },
    -- Float term
    TerminalBorder          = { link = 'SagaBorder' },
    TerminalNormal          = { link = 'SagaNormal' },
    -- Highlight word
    TSDefinitionUsage       = { bg = colors.light_dimmest },

    -- GitSigns
    GitSignsAdd             = { fg = colors.light_dimmest },
    GitSignsChange          = { fg = colors.light_dimmest },

    -- nvim-cmp
    CmpItemKind             = { fg = colors.blue_light },
    CmpItemMenuDefault      = { fg = colors.blue_light },
    CmpItemAbbrMatch        = { fg = colors.purple, bold = true },
    CmpItemAbbrMatchFuzzy   = { link = 'CmpItemAbbrMatch' },
    CmpItemAbbrDeprecated   = { fg = colors.red_soft },

    -- SourceGraph Cody
    CmpItemKindCody         = { fg = colors.magenta },
    CmpItemKindCodyDefault  = { fg = colors.magenta },



  },
  theme = "auto",   -- default, based on vim.o.background, alternatives: "light", "dark"
  contrast = "low", -- default, alternatives: "medium", "high"
})

-- setup must be called before loading
vim.cmd("colorscheme leaf")
